<?php
$this->_param['listColSth'] = ':id, :date, :ip, :host, :port, :password';
$this->_param['listCol'] = 'id, date, ip, host, port, password';
$this->_param['listColT'] = 't.id, t.date, t.ip, t.host, t.port, t.password';
$this->_param['listColPrimary'] = 'id';
$this->_param['listColTPrimary'] = 't.id';
$this->_param['listColTWherePrimary'] = 'id = :id ';
$this->_param['primary']['0'] = 'id';
$this->_param['colsField']['1'] = 'id';
$this->_param['colsField']['2'] = 'date';
$this->_param['colsField']['3'] = 'ip';
$this->_param['colsField']['4'] = 'host';
$this->_param['colsField']['5'] = 'port';
$this->_param['colsField']['6'] = 'password';
$this->_param['colsType']['1'] = 'int';
$this->_param['colsType']['2'] = 'date';
$this->_param['colsType']['3'] = 'string';
$this->_param['colsType']['4'] = 'string';
$this->_param['colsType']['5'] = 'int';
$this->_param['colsType']['6'] = 'string';
$this->_param['colsPosition']['id'] = '1';
$this->_param['colsPosition']['date'] = '2';
$this->_param['colsPosition']['ip'] = '3';
$this->_param['colsPosition']['host'] = '4';
$this->_param['colsPosition']['port'] = '5';
$this->_param['colsPosition']['password'] = '6';
